name: carpenter-pro
region: nyc
services:
  - name: api
    environment_slug: node-js
    github:
      repo: bradz86/carpenter-pro
      branch: main
      deploy_on_push: true
    source_dir: /backend
    build_command: npm install
    run_command: npm start
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 3000
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 5
      failure_threshold: 3
      success_threshold: 1
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "3000"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: BRIGHT_DATA_USERNAME
        scope: RUN_TIME
        value: "REPLACE_WITH_YOUR_USERNAME"
        type: SECRET
      - key: BRIGHT_DATA_PASSWORD
        scope: RUN_TIME
        value: "REPLACE_WITH_YOUR_PASSWORD"
        type: SECRET
      - key: ADMIN_KEY
        scope: RUN_TIME
        value: "REPLACE_WITH_SECURE_KEY"
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        value: "REPLACE_WITH_JWT_SECRET"
        type: SECRET
databases:
  - name: db
    engine: PG
    production: false
    version: "16"
    size: db-s-dev-database
    num_nodes: 1
